---
- name: Restart the service
  win_service:
    name: "{{ jenkins_slave_service_name }}"
    state: restarted

- name: Update the service config
  win_template:
    src: jenkins-slave.j2
    dest: "{{ jenkins_slave_home_dir }}/jenkins-slave.xml"