---
- name: Get Jenkins Slave service info
  win_service:
    name: Jenkins_Slave
  register: service_info

- name: Test Jenkins Slave service is installed
  assert:
    that:
      - service_info.exists == true

#- debug:
#    msg: '{{ jenkins_slave_home_dir }}'
#    msg: 'FOO_VAR: {{ foo_var }}, BAR_VAR: {{ bar_var }}'

- name: Get config file
  win_lineinfile:
    path: '{{ jenkins_slave_home_dir }}/jenkins-slave.xml'
    regex: '<arguments>'
    state: absent
    check_mode: yes
    changed_when: false
    register: out

- debug:
    msg: '{{ out }}'

#- name: Test config file has valid secret
#  assert:
#    that:
#      - out.found