---
- name: Get Jenkins Slave service info
  win_service:
    name: Jenkins_Slave
  register: service_info

- name: Test Jenkins Slave service is installed
  assert:
    that:
      - service_info.exists == true

#- debug:
#    msg: '{{ jenkins_slave_home_dir }}'
#    msg: 'FOO_VAR: {{ foo_var }}, BAR_VAR: {{ bar_var }}'


- name: Get Jenkins Slave config file
  win_shell: cat jenkins-slave.xml
  args:
    chdir: '{{ jenkins_slave_home_dir }}'
  register: out

- name: Test config file has valid secret
  assert:
    that:
      - in out.stdout.find('-secret XYZ')

- debug:
    msg: '{{ out }}'
