---
- name: Get Jenkins Slave service info
  win_service:
    name: Jenkins_Slave
  register: service_info

- name: Test Jenkins Slave service is installed
  assert:
    that:
      - service_info.exists == true

- debug:
    msg: '{{ jenkins_slave_home_dir }}'

#- name: Test config file has valid secret
#  win_lineinfile:
#    path: '{{ jenkins_slave_home_dir }}/jenkins-slave.xml'
#    regex: '<arguments>'
#    state: present