---
- name: Add OS specific variables
  include_vars: '{{ loop_vars }}'
  with_first_found:
    - files:
        - '{{ ansible_os_family }}.yml'
        - 'defaults.yml'
      paths:
        - 'vars'
  loop_control:
    loop_var: loop_vars

- name: Include OS specific tasks
  include_tasks: '{{ loop_distribution }}'
  with_first_found:
    - files:
        - 'main.yml'
        - '../defaults.yml'
      paths:
        - '{{ ansible_os_family }}'
  loop_control:
    loop_var: loop_distribution
