---
- debug:
    msg: 'ansible_distribution: {{ ansible_distribution }}'

- debug:
    msg: 'ansible_distribution_version: {{ ansible_distribution_version }}'

- debug:
    msg: 'ansible_distribution_major_version: {{ ansible_distribution_major_version }}'

- debug:
    msg: 'ansible_system: {{ ansible_system }}'

- debug:
    msg: 'ansible_system: {{ ansible_system }}'

#- name: Add OS specific variables
#  include_vars: '{{ loop_vars }}'
#  with_first_found:
#    - files:
#        - '{{ distribution }}-{{ distribution_version }}.yml'
#        - '{{ distribution }}-{{ distribution_major_version }}.yml'
#        - '{{ distribution }}.yml'
#        - '{{ ansible_os_family }}.yml'
#        - '{{ ansible_system }}.yml'
#        - 'defaults.yml'
#        - 'main.yml'
#      paths:
#        - 'vars'
#  loop_control:
#    loop_var: loop_vars
#  vars:
#    distribution: '{{ ansible_distribution }}'
#    distribution_version: '{{ ansible_distribution_version }}'
#    distribution_major_version: '{{ ansible_distribution_major_version }}'
#  tags:
#    - configuration
#    - packages

- name: Include provision tasks
  include_tasks: provision.yml

- name: Include configure tasks
  include_tasks: configure.yml