---
- name: Add OS specific variables
#  include_vars: '{{ loop_vars }}'
  with_first_found:
    - files:
        - '{{ ansible_os_family }}.yml'
        - 'defaults.yml'
      paths:
        - 'vars'
#  loop_control:
#    loop_var: loop_vars
#  vars:
#    distribution: '{{ ansible_distribution }}'
#    distribution_version: '{{ ansible_distribution_version }}'
#    distribution_major_version: '{{ ansible_distribution_major_version }}'
#  tags:
#    - configuration
#    - packages

- name: Include provision tasks
  include_tasks: provision.yml

- name: Include configure tasks
  include_tasks: configure.yml