---
- name: Remove the service
  win_service:
    name: "{{ jenkins_service_name }}"
    state: absent

- name: Create the service home dir
  win_file:
    path: "{{ jenkins_home_dir }}"
    state: directory

- name: Copy the service exe file
  win_copy:
    src: jenkins-slave.exe
    dest: "{{ jenkins_home_dir }}\\jenkins-slave.exe"

- name: Copy the service jar file
  win_copy:
    src: slave.jar
    dest: "{{ jenkins_home_dir }}\\slave.jar"

- name: Install the service
  win_service:
    name: "{{ jenkins_service_name }}"
    path: "{{ jenkins_home_dir }}\\jenkins-slave.exe"

- name: Configure the service
  include_tasks: configure.yml

#- name: Start the service
#  win_service:
#    name: "{{ jenkins_service_name }}"
#    state: started