---
- name: Verify
  hosts: all
  tasks:
    - name: "Include test_jenkins-slave"
      include_role:
        name: "test_jenkins-slave"
      vars:
        jenkins_slave_home_dir: C:\Jenkins_Slave
        jenkins_slave_secret: ABC