---
- name: Verify
  hosts: all
  tasks:
    - name: "Include test_jenkins-slave"
      include_role:
        name: "test_jenkins-slave"
      vars:
#        jenkins_slave_home_dir: '{{ jenkins_slave_home_dir }}'
        jenkins_slave_home_dir: '{{ jenkins_master_url }}'
